export const copy = Object.freeze({
  brand: "CodeMoji",
  tagline: "סוד קטן שנפתח עם הסימן שלך.",
  receivedTitle: "השארתי לך סוד",
  receivedHint: "צייר את הסימן כדי לפתוח",
  openSecret: "פתח את הסוד",
  wrongSign: "זה לא הסימן",
  tryAgain: "נסה שוב",
  secretOpened: "הסוד נפתח",
  sendBack: "שלח סוד בחזרה",
  composeTitle: "מה הסוד?",
  composePlaceholder: "כתוב משהו קטן…",
  chooseSign: "צייר סימן לפתיחה",
  lockSecret: "סגור את הסוד",
  secretReady: "הסוד מוכן לדרך",
  shareNative: "שלח עכשיו",
  shareWhatsapp: "וואטסאפ",
  shareTelegram: "טלגרם",
  copyLink: "העתק קישור",
  copied: "הועתק",
  malformed: "הסוד הזה לא נפתח",
  privacyHint: "נפתח רק עם הסימן.",
  reset: "סוד חדש",
  composeIntroLead: "כתוב סוד. צייר סימן.",
  receiveLandedFor: "הבועה הגיעה אליך"
});
