export const copy = Object.freeze({
  brand: "CodeMoji",
  tagline: "סוד קטן שנפתח עם הקוד פתיחה שלך.",
  receivedTitle: "קיבלת סוד",
  receivedHint: "החליקו את קוד פתיחה",
  openSecret: "פתחו את הסוד",
  wrongSign: "זה לא הקוד פתיחה",
  tryAgain: "נסה שוב",
  secretOpened: "הסוד נפתח",
  sendBack: "שלח סוד בחזרה",
  composeTitle: "מה הסוד?",
  composePlaceholder: "כתוב משהו קטן…",
  chooseSign: "קבעו קוד פתיחה",
  lockSecret: "נעלו את הסוד",
  secretReady: "הסוד מוכן לשיתוף",
  shareNative: "שלחו בוואטסאפ",
  shareWhatsapp: "שלחו בוואטסאפ",
  shareTelegram: "טלגרם",
  copyLink: "העתיקו קישור",
  copied: "הועתק",
  malformed: "הסוד הזה לא נפתח",
  privacyHint: "הקישור לא מציג את הסוד. הוא נפתח רק עם קוד פתיחה.",
  reset: "סוד חדש",
  composeIntroLead: "כותבים סוד, קובעים קוד פתיחה, משתפים.",
  receiveLandedFor: "הבועה הגיעה אליך"
});

